### ISSUE TITLE
MySQL 원격 접속 불가능

### ISSUE THREAD

**Issue by Choi-JJunho** [team-cart-king/jwp-shopping-order#9]
# 🪲 어떤 버그인가요?

- MySQL 원격접속이 이뤄지지 않는다.

## 🤔 예상 결과

- SpringBoot에서 DataSource를 정상적으로 로드해야한다.

## 🔥 실제 결과

- Connection을 잇지 못한다.

## 📸 스크린샷

<img width="1213" alt="image" src="https://github.com/team-cart-king/jwp-shopping-order/assets/49794401/1b094f47-2770-420d-8571-99c7fa00c2f5">

## ✅ TODO

모든 호스트에 대해 접근권한이 존재하는 MySQL 유저를 생성한다.

**Comment by hyena0608** [comment]
<aside>
💡 접속 불가능한 이유

Database에 접근할 수 있는 호스트 IP가 설정되어있지 않기 때문이다.

아래는 추가한 사진이고, 이후 성공적으로 DB 접근이 가능하다.

</aside>

<img src="https://github.com/team-cart-king/jwp-shopping-order/assets/82203978/3572357c-e10e-4666-9680-8385ebe95f23" width=300>

MySQL에 접속해서 아래 명령어를 수행하면 된다 !

```sql
-- 유저 관련 작업 진행 시 MySQL DB를 사용한다.
USE mysql;

-- '서버_PRIVATE_IP'로 들어올 수 있는 '유저_ID' 계정을 만든다.
CREATE USER 유저_ID@서버_PRIVATE_IP identified by '비밀번호';

-- '유저_ID' 계정이 '유저_데이터베이스명'에 접근할 수 있도록 권한을 준다.
GRANT ALL PRIVILEGES ON 유저_데이터베이스명.* TO 유저_ID@서버_PRIVATE_IP;

-- 설정한 권한을 반영한다.
FLUSH PRIVILEGES;
```

끄-읕 👍

**Comment by Choi-JJunho** [comment]
시작 시 mysql DB 사용부분만 추가해주세요 👍

```sql
-- 유저 관련 작업 진행 시 MySQL DB를 사용한다.
USE mysql;
```
